apiVersion: apps/v1
kind: Deployment
metadata:
  name: kudos-deployment
spec:
  replicas: 2
  selector:
      matchLabels:
        app: kudos-app
  template:
    metadata:
      labels:
        app: kudos-app
    spec:
      containers:
      - name: kudos
        image: thedeadman/cfest:kudos-app-1.0.3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kudos-app
  name: kudos-service
spec:
  ports:
    - port: 3042
      targetPort: 3000
  selector: 
    app: kudos-app
  type: LoadBalancer